In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [2]:
df = pd.read_csv("C:/Users/biank/Downloads/car.data")
print(df)

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [3]:
df

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [5]:
df.isnull().sum()

vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['vhigh']=le.fit_transform(df['vhigh'])

df.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0      3   vhigh  2   2  small   med  unacc
1      3   vhigh  2   2  small  high  unacc
2      3   vhigh  2   2    med   low  unacc
3      3   vhigh  2   2    med   med  unacc
4      3   vhigh  2   2    med  high  unacc

In [15]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['vhigh.1']=le.fit_transform(df['vhigh.1'])

df.head()

   vhigh  vhigh.1  2 2.1  small   low  unacc
0      3        3  2   2  small   med  unacc
1      3        3  2   2  small  high  unacc
2      3        3  2   2    med   low  unacc
3      3        3  2   2    med   med  unacc
4      3        3  2   2    med  high  unacc

In [19]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['2']=le.fit_transform(df['2'])

df.head()

   vhigh  vhigh.1  2 2.1  small   low  unacc
0      3        3  0   2  small   med  unacc
1      3        3  0   2  small  high  unacc
2      3        3  0   2    med   low  unacc
3      3        3  0   2    med   med  unacc
4      3        3  0   2    med  high  unacc

In [20]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['2.1']=le.fit_transform(df['2.1'])

df.head()

   vhigh  vhigh.1  2  2.1  small   low  unacc
0      3        3  0    0  small   med  unacc
1      3        3  0    0  small  high  unacc
2      3        3  0    0    med   low  unacc
3      3        3  0    0    med   med  unacc
4      3        3  0    0    med  high  unacc

In [21]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['small']=le.fit_transform(df['small'])

df.head()

   vhigh  vhigh.1  2  2.1  small   low  unacc
0      3        3  0    0      2   med  unacc
1      3        3  0    0      2  high  unacc
2      3        3  0    0      1   low  unacc
3      3        3  0    0      1   med  unacc
4      3        3  0    0      1  high  unacc

In [22]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['low']=le.fit_transform(df['low'])

df.head()

   vhigh  vhigh.1  2  2.1  small  low  unacc
0      3        3  0    0      2    2  unacc
1      3        3  0    0      2    0  unacc
2      3        3  0    0      1    1  unacc
3      3        3  0    0      1    2  unacc
4      3        3  0    0      1    0  unacc

In [23]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['unacc']=le.fit_transform(df['unacc'])

df.head()

   vhigh  vhigh.1  2  2.1  small  low  unacc
0      3        3  0    0      2    2      2
1      3        3  0    0      2    0      2
2      3        3  0    0      1    1      2
3      3        3  0    0      1    2      2
4      3        3  0    0      1    0      2

In [26]:
#Splitting the data into training and test test
X = df.iloc[:,0:6].values
y = df.iloc[:,6].values

Y = pd.get_dummies(y).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [27]:
X

array([[3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       [3, 3, 0, 0, 1, 1],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [28]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [35]:
from tensorflow.keras import models, layers, optimizers
def build_model(): 
    model = models.Sequential()
    model.add(layers.Dense(64, activation='tanh', input_shape=(6,)))
    model.add(layers.Dense(32, activation='tanh'))
    model.add(layers.Dense(16, activation='tanh'))
    model.add(layers.Dense(4, activation='softmax'))
    model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
    
    return model

model = build_model() 

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 64)                448

 dense_13 (Dense)            (None, 32)                2080

 dense_14 (Dense)            (None, 16)                528

 dense_15 (Dense)            (None, 4)                 68

=================================================================
Total params: 3,124
Trainable params: 3,124
Non-trainable params: 0
_________________________________________________________________

In [36]:
# fitting the model and predicting 
# fit network
model_history = model.fit(x=X_train, y=y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

Epoch 1/100
44/44 [==============================] - 2s 16ms/step - loss: 0.4514 - accuracy: 0.6850 - val_loss: 0.3935 - val_accuracy: 0.6965
Epoch 2/100
44/44 [==============================] - 0s 6ms/step - loss: 0.3616 - accuracy: 0.7075 - val_loss: 0.3615 - val_accuracy: 0.6936
Epoch 3/100
44/44 [==============================] - 0s 6ms/step - loss: 0.3342 - accuracy: 0.7089 - val_loss: 0.3401 - val_accuracy: 0.6908
Epoch 4/100
44/44 [==============================] - 0s 6ms/step - loss: 0.3183 - accuracy: 0.7104 - val_loss: 0.3314 - val_accuracy: 0.6879
Epoch 5/100
44/44 [==============================] - 0s 6ms/step - loss: 0.3075 - accuracy: 0.7140 - val_loss: 0.3196 - val_accuracy: 0.7052
Epoch 6/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2967 - accuracy: 0.7270 - val_loss: 0.3107 - val_accuracy: 0.6965
Epoch 7/100
44/44 [==============================] - 0s 7ms/step - loss: 0.2875 - accuracy: 0.7415 - val_loss: 0.3021 - val_accuracy: 0.7168
Epoch 8/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2790 - accuracy: 0.7524 - val_loss: 0.2965 - val_accuracy: 0.7254
Epoch 9/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2717 - accuracy: 0.7603 - val_loss: 0.2892 - val_accuracy: 0.7283
Epoch 10/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2642 - accuracy: 0.7603 - val_loss: 0.2850 - val_accuracy: 0.7254
Epoch 11/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2589 - accuracy: 0.7603 - val_loss: 0.2782 - val_accuracy: 0.7283
Epoch 12/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2515 - accuracy: 0.7654 - val_loss: 0.2746 - val_accuracy: 0.7254
Epoch 13/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2440 - accuracy: 0.7668 - val_loss: 0.2627 - val_accuracy: 0.7283
Epoch 14/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2367 - accuracy: 0.7661 - val_loss: 0.2553 - val_accuracy: 0.7341
Epoch 15/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2284 - accuracy: 0.7697 - val_loss: 0.2467 - val_accuracy: 0.7283
Epoch 16/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2211 - accuracy: 0.7712 - val_loss: 0.2409 - val_accuracy: 0.7428
Epoch 17/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2141 - accuracy: 0.7820 - val_loss: 0.2327 - val_accuracy: 0.7428
Epoch 18/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2069 - accuracy: 0.7972 - val_loss: 0.2276 - val_accuracy: 0.7630
Epoch 19/100
44/44 [==============================] - 0s 6ms/step - loss: 0.2017 - accuracy: 0.8059 - val_loss: 0.2213 - val_accuracy: 0.7746
Epoch 20/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1959 - accuracy: 0.8132 - val_loss: 0.2151 - val_accuracy: 0.7919
Epoch 21/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1910 - accuracy: 0.8255 - val_loss: 0.2087 - val_accuracy: 0.7919
Epoch 22/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1884 - accuracy: 0.8182 - val_loss: 0.2077 - val_accuracy: 0.7977
Epoch 23/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1838 - accuracy: 0.8313 - val_loss: 0.2061 - val_accuracy: 0.7919
Epoch 24/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1810 - accuracy: 0.8277 - val_loss: 0.1988 - val_accuracy: 0.8035
Epoch 25/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1765 - accuracy: 0.8320 - val_loss: 0.1969 - val_accuracy: 0.8237
Epoch 26/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1744 - accuracy: 0.8306 - val_loss: 0.1874 - val_accuracy: 0.8237
Epoch 27/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1708 - accuracy: 0.8371 - val_loss: 0.1864 - val_accuracy: 0.8410
Epoch 28/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1674 - accuracy: 0.8364 - val_loss: 0.1811 - val_accuracy: 0.8295
Epoch 29/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1642 - accuracy: 0.8450 - val_loss: 0.1892 - val_accuracy: 0.8064
Epoch 30/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1611 - accuracy: 0.8523 - val_loss: 0.1766 - val_accuracy: 0.8092
Epoch 31/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1583 - accuracy: 0.8479 - val_loss: 0.1771 - val_accuracy: 0.8266
Epoch 32/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1558 - accuracy: 0.8545 - val_loss: 0.1709 - val_accuracy: 0.8295
Epoch 33/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1519 - accuracy: 0.8530 - val_loss: 0.1733 - val_accuracy: 0.8410
Epoch 34/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1501 - accuracy: 0.8617 - val_loss: 0.1769 - val_accuracy: 0.8006
Epoch 35/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1466 - accuracy: 0.8610 - val_loss: 0.1862 - val_accuracy: 0.8208
Epoch 36/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1435 - accuracy: 0.8755 - val_loss: 0.1597 - val_accuracy: 0.8584
Epoch 37/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1426 - accuracy: 0.8776 - val_loss: 0.1566 - val_accuracy: 0.8613
Epoch 38/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1391 - accuracy: 0.8747 - val_loss: 0.1519 - val_accuracy: 0.8671
Epoch 39/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1365 - accuracy: 0.8820 - val_loss: 0.1568 - val_accuracy: 0.8468
Epoch 40/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1329 - accuracy: 0.8914 - val_loss: 0.1896 - val_accuracy: 0.7861
Epoch 41/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1331 - accuracy: 0.8863 - val_loss: 0.1619 - val_accuracy: 0.8584
Epoch 42/100
44/44 [==============================] - 0s 5ms/step - loss: 0.1291 - accuracy: 0.9001 - val_loss: 0.1660 - val_accuracy: 0.8064
Epoch 43/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1255 - accuracy: 0.8950 - val_loss: 0.1444 - val_accuracy: 0.8728
Epoch 44/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1241 - accuracy: 0.8986 - val_loss: 0.1556 - val_accuracy: 0.8584
Epoch 45/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1234 - accuracy: 0.9015 - val_loss: 0.1464 - val_accuracy: 0.8555
Epoch 46/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1211 - accuracy: 0.9037 - val_loss: 0.1634 - val_accuracy: 0.8150
Epoch 47/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1175 - accuracy: 0.9044 - val_loss: 0.1405 - val_accuracy: 0.8757
Epoch 48/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1149 - accuracy: 0.9124 - val_loss: 0.1350 - val_accuracy: 0.8786
Epoch 49/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1128 - accuracy: 0.9080 - val_loss: 0.1261 - val_accuracy: 0.8902
Epoch 50/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1106 - accuracy: 0.9153 - val_loss: 0.1554 - val_accuracy: 0.8295
Epoch 51/100
44/44 [==============================] - 0s 7ms/step - loss: 0.1094 - accuracy: 0.9124 - val_loss: 0.1367 - val_accuracy: 0.8613
Epoch 52/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1086 - accuracy: 0.9117 - val_loss: 0.1253 - val_accuracy: 0.8960
Epoch 53/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1061 - accuracy: 0.9175 - val_loss: 0.1308 - val_accuracy: 0.8844
Epoch 54/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1041 - accuracy: 0.9153 - val_loss: 0.1244 - val_accuracy: 0.8728
Epoch 55/100
44/44 [==============================] - 0s 6ms/step - loss: 0.1002 - accuracy: 0.9261 - val_loss: 0.1147 - val_accuracy: 0.9162
Epoch 56/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0996 - accuracy: 0.9254 - val_loss: 0.1401 - val_accuracy: 0.8382
Epoch 57/100
44/44 [==============================] - 0s 7ms/step - loss: 0.0999 - accuracy: 0.9175 - val_loss: 0.1153 - val_accuracy: 0.9104
Epoch 58/100
44/44 [==============================] - 0s 7ms/step - loss: 0.0977 - accuracy: 0.9269 - val_loss: 0.1252 - val_accuracy: 0.8728
Epoch 59/100
44/44 [==============================] - 0s 7ms/step - loss: 0.0961 - accuracy: 0.9232 - val_loss: 0.1239 - val_accuracy: 0.8728
Epoch 60/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0947 - accuracy: 0.9225 - val_loss: 0.1237 - val_accuracy: 0.8757
Epoch 61/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0927 - accuracy: 0.9211 - val_loss: 0.1167 - val_accuracy: 0.9017
Epoch 62/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0903 - accuracy: 0.9298 - val_loss: 0.1212 - val_accuracy: 0.8786
Epoch 63/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0909 - accuracy: 0.9283 - val_loss: 0.1124 - val_accuracy: 0.8988
Epoch 64/100
44/44 [==============================] - 0s 7ms/step - loss: 0.0885 - accuracy: 0.9305 - val_loss: 0.1085 - val_accuracy: 0.9046
Epoch 65/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0876 - accuracy: 0.9290 - val_loss: 0.1084 - val_accuracy: 0.9191
Epoch 66/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0861 - accuracy: 0.9312 - val_loss: 0.1038 - val_accuracy: 0.9133
Epoch 67/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0833 - accuracy: 0.9348 - val_loss: 0.1180 - val_accuracy: 0.8902
Epoch 68/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0827 - accuracy: 0.9356 - val_loss: 0.0979 - val_accuracy: 0.9364
Epoch 69/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0815 - accuracy: 0.9392 - val_loss: 0.1429 - val_accuracy: 0.8468
Epoch 70/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0807 - accuracy: 0.9428 - val_loss: 0.1008 - val_accuracy: 0.9191
Epoch 71/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0786 - accuracy: 0.9450 - val_loss: 0.1077 - val_accuracy: 0.8988
Epoch 72/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0772 - accuracy: 0.9442 - val_loss: 0.1108 - val_accuracy: 0.8960
Epoch 73/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0751 - accuracy: 0.9479 - val_loss: 0.0930 - val_accuracy: 0.9393
Epoch 74/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0739 - accuracy: 0.9464 - val_loss: 0.0935 - val_accuracy: 0.9306
Epoch 75/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0727 - accuracy: 0.9500 - val_loss: 0.1123 - val_accuracy: 0.9191
Epoch 76/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0707 - accuracy: 0.9573 - val_loss: 0.1000 - val_accuracy: 0.9249
Epoch 77/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0700 - accuracy: 0.9529 - val_loss: 0.0913 - val_accuracy: 0.9422
Epoch 78/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0689 - accuracy: 0.9544 - val_loss: 0.0865 - val_accuracy: 0.9422
Epoch 79/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0668 - accuracy: 0.9616 - val_loss: 0.0884 - val_accuracy: 0.9364
Epoch 80/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0656 - accuracy: 0.9631 - val_loss: 0.0966 - val_accuracy: 0.9277
Epoch 81/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0656 - accuracy: 0.9587 - val_loss: 0.0991 - val_accuracy: 0.9220
Epoch 82/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0652 - accuracy: 0.9551 - val_loss: 0.0824 - val_accuracy: 0.9480
Epoch 83/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0625 - accuracy: 0.9631 - val_loss: 0.0783 - val_accuracy: 0.9538
Epoch 84/100
44/44 [==============================] - 0s 5ms/step - loss: 0.0605 - accuracy: 0.9623 - val_loss: 0.0882 - val_accuracy: 0.9422
Epoch 85/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0597 - accuracy: 0.9674 - val_loss: 0.0859 - val_accuracy: 0.9306
Epoch 86/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0576 - accuracy: 0.9638 - val_loss: 0.0805 - val_accuracy: 0.9509
Epoch 87/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0554 - accuracy: 0.9725 - val_loss: 0.0815 - val_accuracy: 0.9509
Epoch 88/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0563 - accuracy: 0.9652 - val_loss: 0.0726 - val_accuracy: 0.9538
Epoch 89/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0567 - accuracy: 0.9645 - val_loss: 0.0701 - val_accuracy: 0.9566
Epoch 90/100
44/44 [==============================] - 0s 5ms/step - loss: 0.0531 - accuracy: 0.9725 - val_loss: 0.0722 - val_accuracy: 0.9538
Epoch 91/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0531 - accuracy: 0.9747 - val_loss: 0.0732 - val_accuracy: 0.9566
Epoch 92/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0532 - accuracy: 0.9674 - val_loss: 0.0765 - val_accuracy: 0.9538
Epoch 93/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0508 - accuracy: 0.9754 - val_loss: 0.0738 - val_accuracy: 0.9538
Epoch 94/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0500 - accuracy: 0.9761 - val_loss: 0.0698 - val_accuracy: 0.9480
Epoch 95/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0499 - accuracy: 0.9710 - val_loss: 0.0652 - val_accuracy: 0.9624
Epoch 96/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0491 - accuracy: 0.9703 - val_loss: 0.0883 - val_accuracy: 0.9335
Epoch 97/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0464 - accuracy: 0.9761 - val_loss: 0.0686 - val_accuracy: 0.9509
Epoch 98/100
44/44 [==============================] - 0s 7ms/step - loss: 0.0461 - accuracy: 0.9776 - val_loss: 0.0728 - val_accuracy: 0.9393
Epoch 99/100
44/44 [==============================] - 0s 7ms/step - loss: 0.0462 - accuracy: 0.9761 - val_loss: 0.0624 - val_accuracy: 0.9711
Epoch 100/100
44/44 [==============================] - 0s 6ms/step - loss: 0.0445 - accuracy: 0.9768 - val_loss: 0.0781 - val_accuracy: 0.9422
11/11 [==============================] - 0s 3ms/step